name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set Docker image tag based on branch
        id: set-tag
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "TAG=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "Unsupported branch: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Log in to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.HARBOR_REGISTRY }}/paradaux-public/isbetterthandubl.in:${{ steps.set-tag.outputs.TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.HARBOR_REGISTRY }}/paradaux-public/isbetterthandubl.in:${{ steps.set-tag.outputs.TAG }}